### PR TITLE
adjusted selectors for url upload form

### LINKED ISSUE #270: URL uploads not working on "Transfers" pagd
When trying to upload a backup via URL on the Transfers page, clicking the upload button does nothing

### PR DESCRIPTION
**Pull request by jamesros161**
This resolves #270 by fixing the jquery selectors

### CODE REVIEW

File: admin/js/boldgrid-backup-admin-home.js [hunk 1]
```diff
@@ -25,10 +25,10 @@ BOLDGRID.BACKUP.HOME = function( $ ) {
 
 	// Onload event listener.
 	$( function() {
-		var $urlImportSection = $( '#url-import-section' );
+		var $urlImportSection = $( 'div#url-import-section' );
 
 		// On click action for the Upload button.
-		$( '#upload-archive-form' )
+		$( 'div#url-import-section' )
```
Comment (bwmarkle) [inline admin/js/boldgrid-backup-admin-home.js:31]: You just assigned `$urlImportSection` above? Why not just use that variable here?

File: admin/js/boldgrid-backup-admin-home.js [hunk 2]
```diff
@@ -92,7 +92,11 @@ BOLDGRID.BACKUP.HOME = function( $ ) {
 		var $badExtension = $( '#bad_extension' ),
 			$fileSizeWarning = $( '[data-id="upload-backup"]:not(span)' ),
 			$fileTooLarge = $( '#file_too_large' ),
-			$submit = $( $( this ).closest( 'input:submit' ) ),
+			$submit = $(
```
Comment (bwmarkle) [inline admin/js/boldgrid-backup-admin-home.js:95]: Does everything need to be wrapped in the `$(` ?

File: admin/js/boldgrid-backup-admin-home.js (hunk 1 above)
Comment (jamesros161) [reply admin/js/boldgrid-backup-admin-home.js:31]: Probably cause I made that change before I changed the definition above :D. It's been adjusted

File: admin/js/boldgrid-backup-admin-home.js (hunk 2 above)
Comment (jamesros161) [reply admin/js/boldgrid-backup-admin-home.js:95]: Yeah. That's how it was before I changed it. The only change I made was using .parent().find() rather than .closest() because .closest() wasn't giving us the right result.
