### PR TITLE
Fix scheduled jobs not running, and add extra logging

### LINKED ISSUE #612: Jobs queue appears to have been delayed by ~2 days
Review this screenshot:

Image

The problem is that the 2/9 backup and the 2/10 backup was uploaded to google drive on 2/11.
* Was the jobs queue never setup properly? Why the delay? There should have been a jobs queue item that ran on 2/9 to upload the 2/9 backup to google drive.

Assistance is needed to help troubleshoot this.

* Maybe a 'jobs-queue.log' that gets a line added whenever the jobs queue is being ran and or deleted?
* Maybe a 'settings.log' that simply tracks when someone goes into the settings and clicks save?
* Maybe a way to debug and see which jobs are currently in the queue?

### PR DESCRIPTION
**Pull request by jamesros161**
This resolves #612 

The issue turned out to caused by a previous commit: [710cb88](https://github.com/boldgrid/boldgrid-backup/commit/710cb8847d138608d8f9c8990c797a9a1faf7793)

This change was made to remove the cron if there are no scheduled jobs to keep it from running unnecessarily.
However, this didn't account for the fact that when new jobs are added to the list of scheduled jobs, the cron entry
isn't being re-added. This PR will add the cron entry if it doesn't already exist, anytime a job is added to the list of scheduled jobs.

Additionally, I am adding a table to the Total Upkeep > Tools > Cron Log that will display the list of currently scheduled jobs.
image

As for adding a log entry for anytime the settings are changed, that is already present under Total Upkeep > Tools > History
image

Added a `jobs-queue` log file, that logs when a job is added, running, and deleted.
image

### CODE REVIEW

File: admin/class-boldgrid-backup-admin-cron-log.php [hunk 1]
```diff
@@ -136,6 +136,57 @@ public function get_log() {
...
+
+		// Return a message if there are no jobs.
+		if ( empty( $jobs ) ) {
+			return '<p style="font-style:italic">' . esc_html__( 'No jobs scheduled.', 'boldgrid-backup' ) . '</p>';
+		}
+
+		// Generate table heading
+		$markup = sprintf(
+			'<table class="wp-list-table widefat striped">
+				<thead>
```
Comment (bwmarkle) [inline admin/class-boldgrid-backup-admin-cron-log.php:160]: The table HTML is missing a closing </thead> tag. This could cause rendering issues in some browsers. Make sure to properly close all HTML tags.

File: admin/class-boldgrid-backup-admin-cron-log.php [hunk 2]
```diff
@@ -146,9 +197,23 @@ public function get_markup() {
...
-		$markup = '<h2>' . __( 'Latest Cron Notices', 'boldgrid-backup' ) . '</h2>
+		$markup = sprintf(
+			'<h2>%1$s</h2>
+			<p>%2$s %3$s</p>
+			%4$s
+			</tbody>
+			</table>',
+			__( 'Scheduled Jobs', 'boldgrid-backup' ),
+			__( 'If there are any jobs scheduled to run, they will be displayed below.', 'boldgrid-backup' ),
+			__( 'Successfully completed jobs will be removed from the list the next time the cron runs.', 'boldgrid-backup' ),
```
Comment (bwmarkle) [inline admin/class-boldgrid-backup-admin-cron-log.php:212]: Why are these not combined into 1?

Instead of `<p>%2$s %3$s</p>` just have `<p>%2$s</p>`

File: admin/class-boldgrid-backup-admin-cron-log.php [hunk 3]
```diff
@@ -146,9 +197,23 @@ public function get_markup() {
...
+			wp_kses_post( $jobs ),
```
Comment (bwmarkle) [inline admin/class-boldgrid-backup-admin-cron-log.php:213]: `$jobs` may be a `<p>` with a `style` attribute.

```php
// Return a message if there are no jobs.
if ( empty( $jobs ) ) {
	return '<p style="font-style:italic">' . esc_html__( 'No jobs scheduled.', 'boldgrid-backup' ) . '</p>';
}
```

Will `wp_kses_post` strip either the tag or the style attribute?

File: admin/class-boldgrid-backup-admin-jobs.php [hunk 4]
```diff
@@ -87,6 +87,24 @@ public function add( $args ) {
 		$this->set_jobs();
 		$this->jobs[] = $args;
 		$this->save_jobs();
+
+		$this->core->logger->init( 'jobs-queue' );
```
Comment (bwmarkle) [inline admin/class-boldgrid-backup-admin-jobs.php:91]: If you init the `jobs-queue` here, then anywhere else in the code that init `core->logger` will begin writing to that file.

For example, if you had a backup process running, the `core->logger` will be writing to the log file for that backup. Here, you just changed which file it will be writing too... Need to have distinct loggers.

Suggest creating a new property or variable `$jobs_logger`

File: admin/class-boldgrid-backup-admin-jobs.php [hunk 5]
```diff
@@ -162,10 +182,11 @@ public function post_archive_files( $info ) {
...
 		$args = array(
-			'filepath'    => $info['filepath'],
-			'action'      => 'boldgrid_backup_post_jobs_email',
-			'action_data' => $info,
-			'post_action' => 'delete_all_prior',
+			'filepath'     => $info['filepath'],
+			'action'       => 'boldgrid_backup_post_jobs_email',
+			'action_data'  => $info,
+			'post_action'  => 'delete_all_prior',
+			'action_title' => __( 'Send an email after all jobs have been ran', 'boldgrid-backup' ),
```
Comment (bwmarkle) [inline admin/class-boldgrid-backup-admin-jobs.php:189]: The pro plugin is adding jobs too. Instead of having to update all those too, maybe just use the `post_action` as the title if the `action_title` is not set.

**Review by bwmarkle — CHANGES_REQUESTED** [review]

File: admin/class-boldgrid-backup-admin-cron-log.php (hunk 2 above)
Comment (jamesros161) [reply admin/class-boldgrid-backup-admin-cron-log.php:212]: Because then the line would be REALLY long. And if I break down the line inside of the __() function into two separete lines, the wordpress plugin checker throws an error for it not being a single string literal.

File: admin/class-boldgrid-backup-admin-jobs.php (hunk 4 above)
Comment (jamesros161) [reply admin/class-boldgrid-backup-admin-jobs.php:91]: That makes sense. Didn't think of that. Still a little new to the Logger used here. Will do

File: admin/class-boldgrid-backup-admin-jobs.php (hunk 5 above)
Comment (jamesros161) [reply admin/class-boldgrid-backup-admin-jobs.php:189]: I will double check, but I searched for all calls to the method for adding a job, and the only one missing a title was this one.

File: admin/class-boldgrid-backup-admin-cron-log.php (hunk 1 above)
Comment (jamesros161) [reply admin/class-boldgrid-backup-admin-cron-log.php:160]: The closing `</tbody></table>` line is on 185

File: admin/class-boldgrid-backup-admin-cron-log.php (hunk 3 above)
Comment (jamesros161) [reply admin/class-boldgrid-backup-admin-cron-log.php:213]: No. `wp_kses_post` is designed to allow just about anything that is normally allowed inside a post's `post_content` field. Style tags will only be stripped if they are empty. The screenshots

File: admin/class-boldgrid-backup-admin-core.php [hunk 6]
```diff
@@ -741,6 +741,8 @@ public function __construct() {
 
 		$this->remote = new Boldgrid_Backup_Admin_Remote( $this );
 
+		$this->folder_exclusion = new Boldgrid_Backup_Admin_Folder_Exclusion( $this );
```
Comment (bwmarkle) [inline admin/class-boldgrid-backup-admin-core.php:744]: Why was this moved? If for no valid reason, can we undo this change. No reason to have it associated with fixing this issue if it didn't.

File: admin/class-boldgrid-backup-admin-cron-log.php (hunk 1 above)
Comment (bwmarkle) [reply admin/class-boldgrid-backup-admin-cron-log.php:171]: I might be missing something, but I believe the `</thead>` is missing.

**Review by bwmarkle — CHANGES_REQUESTED** [review]

File: admin/class-boldgrid-backup-admin-core.php (hunk 6 above)
Comment (jamesros161) [reply admin/class-boldgrid-backup-admin-core.php:744]: It had to be moved because the 'folder_exclusion' property was undefined in the 'jobs' class when it was later down the list.

**Review by bwmarkle — APPROVED** [review]
