### PR TITLE
Fix logic to get disable functions. Fixes #449

### LINKED ISSUE #449: [Bug] Allow for spaces in disable_functions comma-separated list
**Describe the bug**
If a user's php.ini includes spaces in the `ini_get('disable_functions')` , the plugin will try to use disabled functions, causing PHP Warnings.

**To Reproduce**
1. Create a php.ini with the following line:
`disable_functions = "mail, popen, proc_open, exec, shell_exec, passthru, system"`
2. Enable WP_DEBUG and WP_DEBUG_LOG
3. Install Total Upkeep
4. See errors similar to the following:
`12-Feb-2021 21:06:38 UTC] PHP Warning:  popen() has been disabled for security reasons in /home/jesseo/public_html/support/wp-content/plugins/boldgrid-backup/admin/class-boldgrid-backup-admin-cli.php on line 133`

**Expected behavior**
The function should strip extraneous whitespace from the array of disabled functions for proper matching.

**Additional context**
This issue was reported in the [WordPress.org Forums](https://wordpress.org/support/topic/warning-messages-in-version-1-14-10/)

### PR DESCRIPTION
**Pull request by bwmarkle**

### CODE REVIEW

**Review by jamesros161 — DISMISSED** [review]

File: admin/class-boldgrid-backup-admin-cli.php [hunk 1]
```diff
@@ -50,7 +50,8 @@ public static function get_execution_functions() {
 		}
 
 		// Get the PHP disable_functions list.
-		$disabled = explode( ',', ini_get( 'disable_functions' ) );
+		$disabled = str_replace( ' ', '', ini_get( 'disable_functions' ) );
```
Comment (cssjoe) [inline admin/class-boldgrid-backup-admin-cli.php:53]: You should remove tabs as well.  There could also be returns and line breaks.  Why not use pre_replace or array_walk with trim (which trims all of the whitespace chars).

```
$ php -r '$s = "one, two,\tthree"; var_dump( $s ); var_dump( preg_replace( "/[ \n\r\t\v]/", "", $s ) );'
string(15) "one, two,   three"
string(13) "one,two,three"
```

```
$ php -r '$s = "one, two,\tthree"; var_dump( $s ); function trim_val( &$v ) { $v = trim( $v ); } $a = explode( ",", $s ); array_walk( $a, "trim_val" ); var_dump( $a );'
string(15) "one, two,   three"
array(3) {
  [0]=>
  string(3) "one"
  [1]=>
  string(3) "two"
  [2]=>
  string(5) "three"
}
```

**Review by cssjoe — CHANGES_REQUESTED** [review]
Also account for other whitespace characters.

File: admin/class-boldgrid-backup-admin-cli.php (hunk 1 above)
Comment (bwmarkle) [reply admin/class-boldgrid-backup-admin-cli.php]: Updated in https://github.com/BoldGrid/boldgrid-backup/pull/450/commits/d73e9d056c1e48875860afac369933b09b92e34d

**Review by cssjoe — APPROVED** [review]
